server:
    port: 8888
#spring:
#    config:
#        import: "optional:configserver:http://localhost:8888"
spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:config/